version: '2'
services:
  eurekaserver:
    image:   example/shopping-cart-eurekasvr:0.0.1
    ports:
      - "8761:8761"
  configserver:
    image: example/shopping-cart-confsvr:0.0.1
    ports:
      - "8888:8888"
    environment:
      EUREKASERVER_PORT: 8761
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      ENCRYPT_KEY:       "IMSYMMETRIC"
  zuulserver:
    image: example/shopping-cart-zuulsvr:0.0.1
    ports:
      - "5555:5555"
    environment:
      PROFILE: "default"
      SERVER_PORT: "5555"
      CONFIGSERVER_PORT: 8888
      EUREKASERVER_PORT: 8761
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
#  customerdatabase:
#    image: mysql:5.7
#    ports:
#      - "3383:3306"
#    environment:
#      - MYSQL_DATABASE=customer_local
#      - MYSQL_USER=user
#      - MYSQL_PASSWORD=password
#      - MYSQL_ROOT_PASSWORD=password
#  customerservice:
#      image: example/shopping-cart-customersrv:0.0.1
#      ports:
#        - "8083:8083"
#      environment:
#        PROFILE: "default"
#        SERVER_PORT: "8083"
#        DATABASE_PORT:     5432
#        CONFIGSERVER_PORT: 8888
#        EUREKASERVER_PORT: 8761
#        AUTHSERVER_PORT:   8091
#        CONFIGSERVER_URI: "http://configserver:8888"
#        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
#        ENCRYPT_KEY:       "IMSYMMETRIC"
